name: genui_playground
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  bloc: ^9.2.1
  dart_mappable: ^4.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  genui_agent_repository:
    path: ./packages/genui_agent_repository
  openui: ^0.0.1-dev.2
  openui_core: ^0.0.1-dev.2
  openui_components: ^0.0.1-dev.2
  recase: ^4.1.0
  shadcn_ui: ^0.54.0

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  build_runner: ^2.15.0
  dart_mappable_builder: ^4.8.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
